# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10text_embed.proto\x12\ntext_embed\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x11\x45mbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x32^\n\x14TextEmbeddingService\x12\x46\n\x0cGetEmbedding\x12\x17.text_embed.TextRequest\x1a\x1d.text_embed.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=32
  _globals['_TEXTREQUEST']._serialized_end=59
  _globals['_EMBEDDINGRESPONSE']._serialized_start=61
  _globals['_EMBEDDINGRESPONSE']._serialized_end=100
  _globals['_TEXTEMBEDDINGSERVICE']._serialized_start=102
  _globals['_TEXTEMBEDDINGSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
